using Facet;
using Jex.Domain.Entities;

namespace Jex.Application.Features.Users.Queries.GetUserById;

/// <summary>
/// Public user DTO generated by the Facet source generator.
/// Excludes the PasswordHash field automatically.
/// Facet generates: constructor, static factory, LINQ projection expression — all at compile time with zero runtime overhead.
/// </summary>
[Facet(typeof(User), exclude: [nameof(User.PasswordHash)])]
public partial record UserDto;
